name: Test basic workflow

permissions:
  id-token: write
  contents: read

on: 
  workflow_dispatch:
  schedule:
    - cron: ‘*/5 * * * *’

jobs:
  checkout:
    runs-on: ubuntu-latest
    if: github.event.schedule != null 
    steps:
      - name: Checkout Stage Branch
        uses: actions/checkout@v3
        with:
          ref: stage
      - name: Build And Deploy
        run: |
          echo ls 
          ls
          echo ls ../..
          ls ../..
          echo ls ../../..
          ls ../../..
          ls ../../../runners
          
