name: Test basic workflow

permissions:
  id-token: write
  contents: read

on: 
  workflow_dispatch

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Stage Branch
        uses: actions/checkout@v3
        with:
          ref: stage
          
      - name: Build And Deploy
        run: |
          for i in {1..{{vars.ITERATIONS}}}; do
            echo ls 
            ls
            echo ls ../..
            ls ../..
            echo ls ../../..
            ls ../../..
            ls ../../../runners
            sleep 10
          done
          
          
          
