name: Test basic workflow

permissions:
  id-token: write
  contents: read

on: 
  schedule:
  - cron: '* * * * *'

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Stage Branch
        uses: actions/checkout@v3
        with:
          ref: stage
      - name: Build And Deploy
        run: |
          echo ls 
          ls
          echo ls ../..
          ls ../..
          echo ls ../../..
          ls ../../..
          ls ../../../runners

  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Stage Branch
        uses: actions/checkout@v3
        with:
          ref: stage
      - name: Build And Deploy
        run: |
          sleep 15
          echo ls 
          ls
          echo ls ../..
          ls ../..
          echo ls ../../..
          ls ../../..
          ls ../../../runners
          
